### ISSUE TITLE
Список вопросов

### ISSUE THREAD

**Issue by Victor-Y-Fadeev** [Victor-Y-Fadeev/qreal#10]
Составить список вопросов по QReal.

Добавляйте свои вопросы комментариями к этой задаче.

**Comment by RexTremendaeMajestatis** [comment]
1) как добавить плату в трик?
2) добавление физических датчиков
3) добавление блоков
4) как устроена интерпретация по юсб
5) как конкретоно она устроена в трике
6) по какому принципу раскиданы всякие интерфейсы/формочки и тд
7) как писать генератор
8) как формочки заполнять: как понять что нужно/не нужно
9) как интерпретаци проходит? генерит и отправдяет какой-о файл?
10) что нужно удалить из папки bin чтоб удалились платы из списка чтоб при компиляции заново не собирать
11) баг с путем метамодель

**Comment by Victor-Y-Fadeev** [comment]
Задача устарела.
