### ISSUE TITLE
Собрать

### ISSUE THREAD

**Issue by Victor-Y-Fadeev** [Victor-Y-Fadeev/qreal#11]
Собрать Trik Studio с изменениями из веток: [`iotik-v1-0-common`](https://github.com/Victor-Y-Fadeev/qreal/tree/iotik-v1-0-common), [`iotik-v1-0-editor`](https://github.com/Victor-Y-Fadeev/qreal/tree/iotik-v1-0-editor), [`iotik-v1-0-interpreter`](https://github.com/Victor-Y-Fadeev/qreal/tree/iotik-v1-0-interpreter).

**Comment by RexTremendaeMajestatis** [comment]
Собрали. При помощи Литвинова Юрия Викторовича.
