### ISSUE TITLE
Найти генератор RuC

### ISSUE THREAD

**Issue by Victor-Y-Fadeev** [Victor-Y-Fadeev/qreal#2]
Найти генератор RuC, возможно в старых коммитах.

**Comment by Victor-Y-Fadeev** [comment]
Нет такого.

**Comment by Victor-Y-Fadeev** [comment]
Он есть, ищите!

**Comment by RexTremendaeMajestatis** [comment]
[trikRuCGenerator](https://github.com/AirVan21/qreal/tree/master/plugins/robots/generators/trik/trikRuCGenerator)

**Comment by Victor-Y-Fadeev** [comment]
Интегрирован в QReal.
