### ISSUE TITLE
Список лишних *.t

### ISSUE THREAD

**Issue by Victor-Y-Fadeev** [Victor-Y-Fadeev/qreal#22]
Составить, в качестве комментария к этой задаче, список [`templates`](https://github.com/Victor-Y-Fadeev/qreal/tree/iotik-v1-0-generator/plugins/robots/generators/iotik/iotikRuCGenerator/templates) к удалению.

**Comment by Victor-Y-Fadeev** [comment]
Пустые файлы в отдельный список.

**Comment by Victor-Y-Fadeev** [comment]
Итого 3 списка.

**Comment by RexTremendaeMajestatis** [comment]
.t с комментами
___________________________________________________
say.t
nativeCode.t
led.t
beep.t
encoder.t
call.t
declarationsSectionHeader.t
forwardDewclaration.t
implementation.t
implementationsSectionHeader.t
Down.t
Enter.t
Left.t
Power.t
Right.t
Up.t
time.t
______________________________________________________

пустые .t
______________________________________________________
initialNode.t
conditionsSeparater.t
randomize.t
______________________________________________________
luaPrinting, полагаю, целиком не нужен
На всякий случай рассмотрим эту папку отдельно
.t с комментами
______________________________________________________
boolToString.t
explicitKeyFieldInitializator.t
length.t
methodCall.t
______________________________________________________

**Comment by Victor-Y-Fadeev** [comment]
Так, папки: conditional, engines, functions и luaPrinting; должны остаться без изменений, разве что кроме time.t.

**Comment by Victor-Y-Fadeev** [comment]
Оставить без изменений - signs, subprograms, switch, types, variables

Сохранить (до лучших времен) - threads

Требуется модификация - sensors, wait, templates

**Comment by RexTremendaeMajestatis** [comment]
Закрыто.
