### ISSUE TITLE
Отправить файлы на ЙоТик

### ISSUE THREAD

**Issue by Victor-Y-Fadeev** [Victor-Y-Fadeev/qreal#24]
Научиться отправлять сгенерированный файл и конфигурацию датчиков на ЙоТик.

**Comment by RexTremendaeMajestatis** [comment]
файлик конфигурации портов
1-я строка servos и 4 цифры НЕ МЕНЯТЬ НИКОГДА
digital N - кол-во цифровых датчиков
и дальше N строк, в каждой 4 цифры:
1 - ID датчика (отсчет с нуля)
2 - номер датчика (тип) в sensormap.h
3 & 4 - ножки датчика. всегда писать две ножки (14 и 15)
analog N - аналоговый датчик 
дальше N строк по две цифры:
1 - ID датчика
2 - тип (тоже в sensormap.h) нумерация может пересекаться

**Comment by Victor-Y-Fadeev** [comment]
Отправили.
