### ISSUE TITLE
Примеры RuC

### ISSUE THREAD

**Issue by Victor-Y-Fadeev** [Victor-Y-Fadeev/qreal#4]
Найти или написать примеры программ на RuC для контроллера Trik. Ссылка на репозиторий [RuC](https://github.com/andrey-terekhov/RuC).

**Comment by Victor-Y-Fadeev** [comment]
Ссылка на собирающийся [RuC](https://github.com/ReDFoX43rus/RuC).

Собирать через `make`. Имя файла для компиляции указывается в начале [`./RuC/main.c`](https://github.com/ReDFoX43rus/RuC/blob/master/RuC/main.c).

Команда запуска:
```
$ ./ruc
```

**Comment by fedorovplaton** [comment]
Разобрались с синтаксисом RuC.
